- // MIR for `do_not_miscompile_mut_ref` before InstCombine
+ // MIR for `do_not_miscompile_mut_ref` after InstCombine
  
  fn do_not_miscompile_mut_ref() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/inst_combine_deref.rs:65:32: 65:32
      let _1: u32;                         // in scope 0 at $DIR/inst_combine_deref.rs:66:9: 66:10
      let _4: &u32;                        // in scope 0 at $DIR/inst_combine_deref.rs:69:29: 69:31
      let _6: &u32;                        // in scope 0 at $DIR/inst_combine_deref.rs:70:19: 70:21
      let mut _8: *const u32;              // in scope 0 at $DIR/inst_combine_deref.rs:73:9: 73:10
      scope 1 {
          debug a => _1;                   // in scope 1 at $DIR/inst_combine_deref.rs:66:9: 66:10
          let _2: u32;                     // in scope 1 at $DIR/inst_combine_deref.rs:67:9: 67:10
          scope 2 {
              debug b => _2;               // in scope 2 at $DIR/inst_combine_deref.rs:67:9: 67:10
              let mut _3: *const u32;      // in scope 2 at $DIR/inst_combine_deref.rs:69:9: 69:14
              scope 3 {
                  debug c => _3;           // in scope 3 at $DIR/inst_combine_deref.rs:69:9: 69:14
                  let _5: &u32;            // in scope 3 at $DIR/inst_combine_deref.rs:70:9: 70:10
                  scope 4 {
                      debug d => _5;       // in scope 4 at $DIR/inst_combine_deref.rs:70:9: 70:10
                      let _7: &u32;        // in scope 4 at $DIR/inst_combine_deref.rs:72:9: 72:10
                      scope 5 {
                          debug x => _7;   // in scope 5 at $DIR/inst_combine_deref.rs:72:9: 72:10
                          let _9: u32;     // in scope 5 at $DIR/inst_combine_deref.rs:74:9: 74:10
                          scope 7 {
                              debug z => _9; // in scope 7 at $DIR/inst_combine_deref.rs:74:9: 74:10
                          }
                      }
                      scope 6 {
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/inst_combine_deref.rs:66:9: 66:10
          _1 = const 1_u32;                // scope 0 at $DIR/inst_combine_deref.rs:66:13: 66:17
          StorageLive(_2);                 // scope 1 at $DIR/inst_combine_deref.rs:67:9: 67:10
          _2 = const 2_u32;                // scope 1 at $DIR/inst_combine_deref.rs:67:13: 67:17
          StorageLive(_3);                 // scope 2 at $DIR/inst_combine_deref.rs:69:9: 69:14
          StorageLive(_4);                 // scope 2 at $DIR/inst_combine_deref.rs:69:29: 69:31
          _4 = &_1;                        // scope 2 at $DIR/inst_combine_deref.rs:69:29: 69:31
          _3 = &raw const (*_4);           // scope 2 at $DIR/inst_combine_deref.rs:69:29: 69:31
          StorageDead(_4);                 // scope 2 at $DIR/inst_combine_deref.rs:69:31: 69:32
          StorageLive(_5);                 // scope 3 at $DIR/inst_combine_deref.rs:70:9: 70:10
          StorageLive(_6);                 // scope 3 at $DIR/inst_combine_deref.rs:70:19: 70:21
          _6 = &_2;                        // scope 3 at $DIR/inst_combine_deref.rs:70:19: 70:21
-         _5 = &(*_6);                     // scope 3 at $DIR/inst_combine_deref.rs:70:19: 70:21
+         _5 = _6;                         // scope 3 at $DIR/inst_combine_deref.rs:70:19: 70:21
          StorageDead(_6);                 // scope 3 at $DIR/inst_combine_deref.rs:70:21: 70:22
          StorageLive(_7);                 // scope 4 at $DIR/inst_combine_deref.rs:72:9: 72:10
          _7 = &(*_3);                     // scope 6 at $DIR/inst_combine_deref.rs:72:22: 72:25
          StorageLive(_8);                 // scope 5 at $DIR/inst_combine_deref.rs:73:9: 73:10
          _8 = &raw const (*_5);           // scope 5 at $DIR/inst_combine_deref.rs:73:9: 73:10
          _3 = move _8;                    // scope 5 at $DIR/inst_combine_deref.rs:73:5: 73:10
          StorageDead(_8);                 // scope 5 at $DIR/inst_combine_deref.rs:73:9: 73:10
          StorageLive(_9);                 // scope 5 at $DIR/inst_combine_deref.rs:74:9: 74:10
          _9 = (*_7);                      // scope 5 at $DIR/inst_combine_deref.rs:74:13: 74:15
          _0 = const ();                   // scope 0 at $DIR/inst_combine_deref.rs:65:32: 75:2
          StorageDead(_9);                 // scope 5 at $DIR/inst_combine_deref.rs:75:1: 75:2
          StorageDead(_7);                 // scope 4 at $DIR/inst_combine_deref.rs:75:1: 75:2
          StorageDead(_5);                 // scope 3 at $DIR/inst_combine_deref.rs:75:1: 75:2
          StorageDead(_3);                 // scope 2 at $DIR/inst_combine_deref.rs:75:1: 75:2
          StorageDead(_2);                 // scope 1 at $DIR/inst_combine_deref.rs:75:1: 75:2
          StorageDead(_1);                 // scope 0 at $DIR/inst_combine_deref.rs:75:1: 75:2
          return;                          // scope 0 at $DIR/inst_combine_deref.rs:75:2: 75:2
      }
  }
  
