- // MIR for `very_deep_opt` before RemoveDeref
+ // MIR for `very_deep_opt` after RemoveDeref
  
  fn very_deep_opt() -> (u64, u64, u64, u64, u64, u64, u64, u64, u64) {
      let mut _0: (u64, u64, u64, u64, u64, u64, u64, u64, u64); // return place in scope 0 at $DIR/remove_deref.rs:63:23: 63:68
      let _1: u64;                         // in scope 0 at $DIR/remove_deref.rs:64:9: 64:11
      let mut _28: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:6: 91:8
      let mut _29: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:10: 91:12
      let mut _30: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:14: 91:16
      let mut _31: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:18: 91:20
      let mut _32: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:22: 91:24
      let mut _33: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:26: 91:28
      let mut _34: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:30: 91:32
      let mut _35: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:34: 91:36
      let mut _36: u64;                    // in scope 0 at $DIR/remove_deref.rs:91:38: 91:40
      scope 1 {
          debug x1 => _1;                  // in scope 1 at $DIR/remove_deref.rs:64:9: 64:11
          let _2: u64;                     // in scope 1 at $DIR/remove_deref.rs:65:9: 65:11
          scope 2 {
              debug x2 => _2;              // in scope 2 at $DIR/remove_deref.rs:65:9: 65:11
              let _3: u64;                 // in scope 2 at $DIR/remove_deref.rs:66:9: 66:11
              scope 3 {
                  debug x3 => _3;          // in scope 3 at $DIR/remove_deref.rs:66:9: 66:11
                  let _4: u64;             // in scope 3 at $DIR/remove_deref.rs:67:9: 67:11
                  scope 4 {
                      debug x4 => _4;      // in scope 4 at $DIR/remove_deref.rs:67:9: 67:11
                      let _5: u64;         // in scope 4 at $DIR/remove_deref.rs:68:9: 68:11
                      scope 5 {
                          debug x5 => _5;  // in scope 5 at $DIR/remove_deref.rs:68:9: 68:11
                          let _6: u64;     // in scope 5 at $DIR/remove_deref.rs:69:9: 69:11
                          scope 6 {
                              debug x6 => _6; // in scope 6 at $DIR/remove_deref.rs:69:9: 69:11
                              let _7: u64; // in scope 6 at $DIR/remove_deref.rs:70:9: 70:11
                              scope 7 {
                                  debug x7 => _7; // in scope 7 at $DIR/remove_deref.rs:70:9: 70:11
                                  let _8: u64; // in scope 7 at $DIR/remove_deref.rs:71:9: 71:11
                                  scope 8 {
                                      debug x8 => _8; // in scope 8 at $DIR/remove_deref.rs:71:9: 71:11
                                      let _9: u64; // in scope 8 at $DIR/remove_deref.rs:72:9: 72:11
                                      scope 9 {
                                          debug x9 => _9; // in scope 9 at $DIR/remove_deref.rs:72:9: 72:11
                                          let _10: &u64; // in scope 9 at $DIR/remove_deref.rs:73:9: 73:11
                                          scope 10 {
                                              debug y1 => _10; // in scope 10 at $DIR/remove_deref.rs:73:9: 73:11
                                              let _11: &u64; // in scope 10 at $DIR/remove_deref.rs:74:9: 74:11
                                              scope 11 {
                                                  debug y2 => _11; // in scope 11 at $DIR/remove_deref.rs:74:9: 74:11
                                                  let _12: &u64; // in scope 11 at $DIR/remove_deref.rs:75:9: 75:11
                                                  scope 12 {
                                                      debug y3 => _12; // in scope 12 at $DIR/remove_deref.rs:75:9: 75:11
                                                      let _13: &u64; // in scope 12 at $DIR/remove_deref.rs:76:9: 76:11
                                                      scope 13 {
                                                          debug y4 => _13; // in scope 13 at $DIR/remove_deref.rs:76:9: 76:11
                                                          let _14: &u64; // in scope 13 at $DIR/remove_deref.rs:77:9: 77:11
                                                          scope 14 {
                                                              debug y5 => _14; // in scope 14 at $DIR/remove_deref.rs:77:9: 77:11
                                                              let _15: &u64; // in scope 14 at $DIR/remove_deref.rs:78:9: 78:11
                                                              scope 15 {
                                                                  debug y6 => _15; // in scope 15 at $DIR/remove_deref.rs:78:9: 78:11
                                                                  let _16: &u64; // in scope 15 at $DIR/remove_deref.rs:79:9: 79:11
                                                                  scope 16 {
                                                                      debug y7 => _16; // in scope 16 at $DIR/remove_deref.rs:79:9: 79:11
                                                                      let _17: &u64; // in scope 16 at $DIR/remove_deref.rs:80:9: 80:11
                                                                      scope 17 {
                                                                          debug y8 => _17; // in scope 17 at $DIR/remove_deref.rs:80:9: 80:11
                                                                          let _18: &u64; // in scope 17 at $DIR/remove_deref.rs:81:9: 81:11
                                                                          scope 18 {
                                                                              debug y9 => _18; // in scope 18 at $DIR/remove_deref.rs:81:9: 81:11
                                                                              let _19: u64; // in scope 18 at $DIR/remove_deref.rs:82:9: 82:11
                                                                              scope 19 {
                                                                                  debug z1 => _19; // in scope 19 at $DIR/remove_deref.rs:82:9: 82:11
                                                                                  let _20: u64; // in scope 19 at $DIR/remove_deref.rs:83:9: 83:11
                                                                                  scope 20 {
                                                                                      debug z2 => _20; // in scope 20 at $DIR/remove_deref.rs:83:9: 83:11
                                                                                      let _21: u64; // in scope 20 at $DIR/remove_deref.rs:84:9: 84:11
                                                                                      scope 21 {
                                                                                          debug z3 => _21; // in scope 21 at $DIR/remove_deref.rs:84:9: 84:11
                                                                                          let _22: u64; // in scope 21 at $DIR/remove_deref.rs:85:9: 85:11
                                                                                          scope 22 {
                                                                                              debug z4 => _22; // in scope 22 at $DIR/remove_deref.rs:85:9: 85:11
                                                                                              let _23: u64; // in scope 22 at $DIR/remove_deref.rs:86:9: 86:11
                                                                                              scope 23 {
                                                                                                  debug z5 => _23; // in scope 23 at $DIR/remove_deref.rs:86:9: 86:11
                                                                                                  let _24: u64; // in scope 23 at $DIR/remove_deref.rs:87:9: 87:11
                                                                                                  scope 24 {
                                                                                                      debug z6 => _24; // in scope 24 at $DIR/remove_deref.rs:87:9: 87:11
                                                                                                      let _25: u64; // in scope 24 at $DIR/remove_deref.rs:88:9: 88:11
                                                                                                      scope 25 {
                                                                                                          debug z7 => _25; // in scope 25 at $DIR/remove_deref.rs:88:9: 88:11
                                                                                                          let _26: u64; // in scope 25 at $DIR/remove_deref.rs:89:9: 89:11
                                                                                                          scope 26 {
                                                                                                              debug z8 => _26; // in scope 26 at $DIR/remove_deref.rs:89:9: 89:11
                                                                                                              let _27: u64; // in scope 26 at $DIR/remove_deref.rs:90:9: 90:11
                                                                                                              scope 27 {
                                                                                                                  debug z9 => _27; // in scope 27 at $DIR/remove_deref.rs:90:9: 90:11
                                                                                                              }
                                                                                                          }
                                                                                                      }
                                                                                                  }
                                                                                              }
                                                                                          }
                                                                                      }
                                                                                  }
                                                                              }
                                                                          }
                                                                      }
                                                                  }
                                                              }
                                                          }
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/remove_deref.rs:64:9: 64:11
          _1 = const 1_u64;                // scope 0 at $DIR/remove_deref.rs:64:14: 64:15
          StorageLive(_2);                 // scope 1 at $DIR/remove_deref.rs:65:9: 65:11
          _2 = const 2_u64;                // scope 1 at $DIR/remove_deref.rs:65:14: 65:15
          StorageLive(_3);                 // scope 2 at $DIR/remove_deref.rs:66:9: 66:11
          _3 = const 3_u64;                // scope 2 at $DIR/remove_deref.rs:66:14: 66:15
          StorageLive(_4);                 // scope 3 at $DIR/remove_deref.rs:67:9: 67:11
          _4 = const 4_u64;                // scope 3 at $DIR/remove_deref.rs:67:14: 67:15
          StorageLive(_5);                 // scope 4 at $DIR/remove_deref.rs:68:9: 68:11
          _5 = const 5_u64;                // scope 4 at $DIR/remove_deref.rs:68:14: 68:15
          StorageLive(_6);                 // scope 5 at $DIR/remove_deref.rs:69:9: 69:11
          _6 = const 6_u64;                // scope 5 at $DIR/remove_deref.rs:69:14: 69:15
          StorageLive(_7);                 // scope 6 at $DIR/remove_deref.rs:70:9: 70:11
          _7 = const 7_u64;                // scope 6 at $DIR/remove_deref.rs:70:14: 70:15
          StorageLive(_8);                 // scope 7 at $DIR/remove_deref.rs:71:9: 71:11
          _8 = const 8_u64;                // scope 7 at $DIR/remove_deref.rs:71:14: 71:15
          StorageLive(_9);                 // scope 8 at $DIR/remove_deref.rs:72:9: 72:11
          _9 = const 9_u64;                // scope 8 at $DIR/remove_deref.rs:72:14: 72:15
          StorageLive(_10);                // scope 9 at $DIR/remove_deref.rs:73:9: 73:11
          _10 = &_1;                       // scope 9 at $DIR/remove_deref.rs:73:14: 73:17
          StorageLive(_11);                // scope 10 at $DIR/remove_deref.rs:74:9: 74:11
          _11 = &_2;                       // scope 10 at $DIR/remove_deref.rs:74:14: 74:17
          StorageLive(_12);                // scope 11 at $DIR/remove_deref.rs:75:9: 75:11
          _12 = &_3;                       // scope 11 at $DIR/remove_deref.rs:75:14: 75:17
          StorageLive(_13);                // scope 12 at $DIR/remove_deref.rs:76:9: 76:11
          _13 = &_4;                       // scope 12 at $DIR/remove_deref.rs:76:14: 76:17
          StorageLive(_14);                // scope 13 at $DIR/remove_deref.rs:77:9: 77:11
          _14 = &_5;                       // scope 13 at $DIR/remove_deref.rs:77:14: 77:17
          StorageLive(_15);                // scope 14 at $DIR/remove_deref.rs:78:9: 78:11
          _15 = &_6;                       // scope 14 at $DIR/remove_deref.rs:78:14: 78:17
          StorageLive(_16);                // scope 15 at $DIR/remove_deref.rs:79:9: 79:11
          _16 = &_7;                       // scope 15 at $DIR/remove_deref.rs:79:14: 79:17
          StorageLive(_17);                // scope 16 at $DIR/remove_deref.rs:80:9: 80:11
          _17 = &_8;                       // scope 16 at $DIR/remove_deref.rs:80:14: 80:17
          StorageLive(_18);                // scope 17 at $DIR/remove_deref.rs:81:9: 81:11
          _18 = &_9;                       // scope 17 at $DIR/remove_deref.rs:81:14: 81:17
          StorageLive(_19);                // scope 18 at $DIR/remove_deref.rs:82:9: 82:11
-         _19 = (*_10);                    // scope 18 at $DIR/remove_deref.rs:82:14: 82:17
+         _19 = _1;                        // scope 18 at $DIR/remove_deref.rs:82:14: 82:17
          StorageLive(_20);                // scope 19 at $DIR/remove_deref.rs:83:9: 83:11
-         _20 = (*_11);                    // scope 19 at $DIR/remove_deref.rs:83:14: 83:17
+         _20 = _2;                        // scope 19 at $DIR/remove_deref.rs:83:14: 83:17
          StorageLive(_21);                // scope 20 at $DIR/remove_deref.rs:84:9: 84:11
-         _21 = (*_12);                    // scope 20 at $DIR/remove_deref.rs:84:14: 84:17
+         _21 = _3;                        // scope 20 at $DIR/remove_deref.rs:84:14: 84:17
          StorageLive(_22);                // scope 21 at $DIR/remove_deref.rs:85:9: 85:11
-         _22 = (*_13);                    // scope 21 at $DIR/remove_deref.rs:85:14: 85:17
+         _22 = _4;                        // scope 21 at $DIR/remove_deref.rs:85:14: 85:17
          StorageLive(_23);                // scope 22 at $DIR/remove_deref.rs:86:9: 86:11
-         _23 = (*_14);                    // scope 22 at $DIR/remove_deref.rs:86:14: 86:17
+         _23 = _5;                        // scope 22 at $DIR/remove_deref.rs:86:14: 86:17
          StorageLive(_24);                // scope 23 at $DIR/remove_deref.rs:87:9: 87:11
-         _24 = (*_15);                    // scope 23 at $DIR/remove_deref.rs:87:14: 87:17
+         _24 = _6;                        // scope 23 at $DIR/remove_deref.rs:87:14: 87:17
          StorageLive(_25);                // scope 24 at $DIR/remove_deref.rs:88:9: 88:11
-         _25 = (*_16);                    // scope 24 at $DIR/remove_deref.rs:88:14: 88:17
+         _25 = _7;                        // scope 24 at $DIR/remove_deref.rs:88:14: 88:17
          StorageLive(_26);                // scope 25 at $DIR/remove_deref.rs:89:9: 89:11
-         _26 = (*_17);                    // scope 25 at $DIR/remove_deref.rs:89:14: 89:17
+         _26 = _8;                        // scope 25 at $DIR/remove_deref.rs:89:14: 89:17
          StorageLive(_27);                // scope 26 at $DIR/remove_deref.rs:90:9: 90:11
-         _27 = (*_18);                    // scope 26 at $DIR/remove_deref.rs:90:14: 90:17
+         _27 = _9;                        // scope 26 at $DIR/remove_deref.rs:90:14: 90:17
          StorageLive(_28);                // scope 27 at $DIR/remove_deref.rs:91:6: 91:8
          _28 = _19;                       // scope 27 at $DIR/remove_deref.rs:91:6: 91:8
          StorageLive(_29);                // scope 27 at $DIR/remove_deref.rs:91:10: 91:12
          _29 = _20;                       // scope 27 at $DIR/remove_deref.rs:91:10: 91:12
          StorageLive(_30);                // scope 27 at $DIR/remove_deref.rs:91:14: 91:16
          _30 = _21;                       // scope 27 at $DIR/remove_deref.rs:91:14: 91:16
          StorageLive(_31);                // scope 27 at $DIR/remove_deref.rs:91:18: 91:20
          _31 = _22;                       // scope 27 at $DIR/remove_deref.rs:91:18: 91:20
          StorageLive(_32);                // scope 27 at $DIR/remove_deref.rs:91:22: 91:24
          _32 = _23;                       // scope 27 at $DIR/remove_deref.rs:91:22: 91:24
          StorageLive(_33);                // scope 27 at $DIR/remove_deref.rs:91:26: 91:28
          _33 = _24;                       // scope 27 at $DIR/remove_deref.rs:91:26: 91:28
          StorageLive(_34);                // scope 27 at $DIR/remove_deref.rs:91:30: 91:32
          _34 = _25;                       // scope 27 at $DIR/remove_deref.rs:91:30: 91:32
          StorageLive(_35);                // scope 27 at $DIR/remove_deref.rs:91:34: 91:36
          _35 = _26;                       // scope 27 at $DIR/remove_deref.rs:91:34: 91:36
          StorageLive(_36);                // scope 27 at $DIR/remove_deref.rs:91:38: 91:40
          _36 = _27;                       // scope 27 at $DIR/remove_deref.rs:91:38: 91:40
          (_0.0: u64) = move _28;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.1: u64) = move _29;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.2: u64) = move _30;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.3: u64) = move _31;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.4: u64) = move _32;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.5: u64) = move _33;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.6: u64) = move _34;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.7: u64) = move _35;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          (_0.8: u64) = move _36;          // scope 27 at $DIR/remove_deref.rs:91:5: 91:41
          StorageDead(_36);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_35);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_34);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_33);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_32);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_31);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_30);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_29);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_28);                // scope 27 at $DIR/remove_deref.rs:91:40: 91:41
          StorageDead(_27);                // scope 26 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_26);                // scope 25 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_25);                // scope 24 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_24);                // scope 23 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_23);                // scope 22 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_22);                // scope 21 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_21);                // scope 20 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_20);                // scope 19 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_19);                // scope 18 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_18);                // scope 17 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_17);                // scope 16 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_16);                // scope 15 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_15);                // scope 14 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_14);                // scope 13 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_13);                // scope 12 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_12);                // scope 11 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_11);                // scope 10 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_10);                // scope 9 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_9);                 // scope 8 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_8);                 // scope 7 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_7);                 // scope 6 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_6);                 // scope 5 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_5);                 // scope 4 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_4);                 // scope 3 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_3);                 // scope 2 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_2);                 // scope 1 at $DIR/remove_deref.rs:92:1: 92:2
          StorageDead(_1);                 // scope 0 at $DIR/remove_deref.rs:92:1: 92:2
          return;                          // scope 0 at $DIR/remove_deref.rs:92:2: 92:2
      }
  }
  
