- // MIR for `id` before SimplifyArmIdentity
+ // MIR for `id` after SimplifyArmIdentity
  
  fn id(_1: std::result::Result<u8, i32>) -> MyResult<u8, i32> {
      debug r => _1;                       // in scope 0 at $DIR/simplify-arm-same-layout.rs:9:7: 9:8
      let mut _0: MyResult<u8, i32>;       // return place in scope 0 at $DIR/simplify-arm-same-layout.rs:9:30: 9:47
      let mut _2: isize;                   // in scope 0 at $DIR/simplify-arm-same-layout.rs:11:9: 11:14
      let _3: u8;                          // in scope 0 at $DIR/simplify-arm-same-layout.rs:11:12: 11:13
      let mut _4: u8;                      // in scope 0 at $DIR/simplify-arm-same-layout.rs:11:31: 11:32
      let _5: i32;                         // in scope 0 at $DIR/simplify-arm-same-layout.rs:12:13: 12:14
      let mut _6: i32;                     // in scope 0 at $DIR/simplify-arm-same-layout.rs:12:33: 12:34
      scope 1 {
          debug x => _3;                   // in scope 1 at $DIR/simplify-arm-same-layout.rs:11:12: 11:13
      }
      scope 2 {
          debug y => _5;                   // in scope 2 at $DIR/simplify-arm-same-layout.rs:12:13: 12:14
      }
  
      bb0: {
          _2 = discriminant(_1);           // scope 0 at $DIR/simplify-arm-same-layout.rs:11:9: 11:14
          switchInt(move _2) -> [0_isize: bb3, 1_isize: bb1, otherwise: bb2]; // scope 0 at $DIR/simplify-arm-same-layout.rs:11:9: 11:14
      }
  
      bb1: {
          StorageLive(_5);                 // scope 0 at $DIR/simplify-arm-same-layout.rs:12:13: 12:14
          _5 = ((_1 as Err).0: i32);       // scope 0 at $DIR/simplify-arm-same-layout.rs:12:13: 12:14
          StorageLive(_6);                 // scope 2 at $DIR/simplify-arm-same-layout.rs:12:33: 12:34
          _6 = _5;                         // scope 2 at $DIR/simplify-arm-same-layout.rs:12:33: 12:34
          ((_0 as Err).0: i32) = move _6;  // scope 2 at $DIR/simplify-arm-same-layout.rs:12:19: 12:35
          discriminant(_0) = 1;            // scope 2 at $DIR/simplify-arm-same-layout.rs:12:19: 12:35
          StorageDead(_6);                 // scope 2 at $DIR/simplify-arm-same-layout.rs:12:34: 12:35
          StorageDead(_5);                 // scope 0 at $DIR/simplify-arm-same-layout.rs:12:34: 12:35
          goto -> bb4;                     // scope 0 at $DIR/simplify-arm-same-layout.rs:10:5: 13:6
      }
  
      bb2: {
          unreachable;                     // scope 0 at $DIR/simplify-arm-same-layout.rs:10:11: 10:12
      }
  
      bb3: {
          StorageLive(_3);                 // scope 0 at $DIR/simplify-arm-same-layout.rs:11:12: 11:13
          _3 = ((_1 as Ok).0: u8);         // scope 0 at $DIR/simplify-arm-same-layout.rs:11:12: 11:13
          StorageLive(_4);                 // scope 1 at $DIR/simplify-arm-same-layout.rs:11:31: 11:32
          _4 = _3;                         // scope 1 at $DIR/simplify-arm-same-layout.rs:11:31: 11:32
          ((_0 as Ok).0: u8) = move _4;    // scope 1 at $DIR/simplify-arm-same-layout.rs:11:18: 11:33
          discriminant(_0) = 0;            // scope 1 at $DIR/simplify-arm-same-layout.rs:11:18: 11:33
          StorageDead(_4);                 // scope 1 at $DIR/simplify-arm-same-layout.rs:11:32: 11:33
          StorageDead(_3);                 // scope 0 at $DIR/simplify-arm-same-layout.rs:11:32: 11:33
          goto -> bb4;                     // scope 0 at $DIR/simplify-arm-same-layout.rs:10:5: 13:6
      }
  
      bb4: {
          return;                          // scope 0 at $DIR/simplify-arm-same-layout.rs:14:2: 14:2
      }
  }
  
